name       : python-m2r
version    : 0.2.1
release    : 4
source     :
    - https://github.com/miyakogi/m2r/archive/v0.2.1.tar.gz : 9286c1a5d7548f34b0a12017444e4c441781bef4b71f321f723e314b76b6c498
homepage   : https://github.com/miyakogi/m2r
license    : MIT
component  : programming.python
summary    : Markdown to reStructuredText converter
description: |
    M2R converts a markdown file including reStructuredText (rst) markups to a valid rst format.
builddeps  :
    - pygments
    - python-docutils
    - python-mistune
    - python-mock
rundeps    :
    - python-docutils
    - python-mistune
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
